# Generated by Django 4.2.1 on 2023-05-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.CharField(max_length=64)),
                ("polish", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="WordSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.TextField()),
                ("polish", models.TextField()),
                ("words", models.ManyToManyField(to="api.translation")),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
