# Generated by Django 4.2.1 on 2023-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fallingwordsgamesession',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='memorygamesession',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='raceactivegame',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='race_active_games', to='api.gameplayer'),
        ),
        migrations.AlterField(
            model_name='racegamesession',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
