# Generated by Django 4.2.1 on 2023-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallingwordsgamesession',
            name='game_name',
            field=models.CharField(choices=[('memory', 'Memory'), ('falling_words', 'Falling Words'), ('race', 'Race')], default='memory', max_length=20),
        ),
        migrations.AddField(
            model_name='memorygamesession',
            name='game_name',
            field=models.CharField(choices=[('memory', 'Memory'), ('falling_words', 'Falling Words'), ('race', 'Race')], default='memory', max_length=20),
        ),
        migrations.AddField(
            model_name='racegamesession',
            name='game_name',
            field=models.CharField(choices=[('memory', 'Memory'), ('falling_words', 'Falling Words'), ('race', 'Race')], default='memory', max_length=20),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='game_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
