# Generated by Django 4.2.1 on 2023-09-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fallingwordsgamesession_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
