# Generated by Django 4.2.1 on 2023-09-09 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_raceactivegame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceactivegame',
            name='users',
        ),
        migrations.AlterField(
            model_name='memorygamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='raceactivegame',
            name='players',
            field=models.ManyToManyField(related_name='race_active_games', to='api.gameplayer'),
        ),
    ]
