# Generated by Django 4.2.1 on 2023-09-09 10:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_raceactivegame_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='good_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='raceactivegame',
            name='wordset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.wordset'),
        ),
        migrations.AlterField(
            model_name='memorygamesession',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='RaceGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('opponents', models.ManyToManyField(blank=True, related_name='race_game_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('wordset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.wordset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
