# Generated by Django 4.2.1 on 2023-09-09 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gameplayer_good_answers_raceactivegame_wordset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='racegamesession',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='memorygamesession',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='raceactivegame',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, related_name='race_active_games', to='api.gameplayer'),
        ),
    ]
