# Generated by Django 4.2.1 on 2023-09-25 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customuser_avatar_friendship_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_translations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
