# Generated by Django 4.2.1 on 2023-09-26 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_translation_starred_by_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_answers_counter', models.PositiveIntegerField(default=0)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
