# Generated by Django 4.2.1 on 2023-09-26 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_answercounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceactivegame',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
