# Generated by Django 4.2.1 on 2023-09-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_raceactivegame_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationuseraccuracycounter',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='translationuseraccuracycounter',
            name='bad_answers_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordset',
            name='category',
            field=models.CharField(default='General', max_length=64),
        ),
        migrations.AddField(
            model_name='wordset',
            name='difficulty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars'),
        ),
    ]
