# Generated by Django 4.2.1 on 2023-10-01 14:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_translationuseraccuracycounter_accuracy'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSetUserAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wordset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wordset')),
            ],
            options={
                'unique_together': {('user', 'wordset')},
            },
        ),
    ]
