# Generated by Django 4.2.1 on 2023-10-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_wordsetuseraccuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsetuseraccuracy',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
