# Generated by Django 4.2.1 on 2023-11-12 22:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20231105_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingWordsGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('accuracy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('timestamp', models.DateTimeField()),
                ('game_name', models.CharField(choices=[('memory', 'Memory'), ('falling_words', 'Falling Words'), ('race', 'Race')], default='memory', max_length=20)),
                ('opponents', models.ManyToManyField(blank=True, related_name='finding_words_game_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('wordset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.wordset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FindingWordsActiveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_count', models.IntegerField(default=0)),
                ('round_count', models.IntegerField(default=0)),
                ('rounds', models.JSONField()),
                ('players', models.ManyToManyField(blank=True, related_name='finding_Words_active_games', to='api.gameplayer')),
                ('wordset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.wordset')),
            ],
        ),
    ]
