# Generated by Django 4.2.1 on 2023-11-12 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20231105_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='llama',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
