# Generated by Django 4.2.1 on 2023-11-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_customuser_llama"),
        ("api", "0019_findingwordsgamesession_findingwordsactivegame"),
    ]

    operations = []
