# Generated by Django 4.2.1 on 2023-12-09 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def delete_previous_active_sessions(apps, schema_editor):
    RaceActiveGame = apps.get_model('api', 'RaceActiveGame')
    RaceActiveGame.objects.all().delete()

    FindingWordsActiveGame = apps.get_model('api', 'FindingWordsActiveGame')
    FindingWordsActiveGame.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_merge_20231118_1610"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="findingwordsactivegame",
            name="answers_count",
        ),
        migrations.RemoveField(
            model_name="findingwordsactivegame",
            name="id",
        ),
        migrations.RemoveField(
            model_name="findingwordsactivegame",
            name="players",
        ),
        migrations.RemoveField(
            model_name="findingwordsactivegame",
            name="round_count",
        ),
        migrations.RemoveField(
            model_name="findingwordsactivegame",
            name="wordset",
        ),
        migrations.RemoveField(
            model_name="raceactivegame",
            name="answers_count",
        ),
        migrations.RemoveField(
            model_name="raceactivegame",
            name="id",
        ),
        migrations.RemoveField(
            model_name="raceactivegame",
            name="players",
        ),
        migrations.RemoveField(
            model_name="raceactivegame",
            name="round_count",
        ),
        migrations.RemoveField(
            model_name="raceactivegame",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="raceactivegame",
            name="wordset",
        ),
        migrations.AddField(
            model_name="waitingroom",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owns_waiting_room",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="waitingroom",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="in_waiting_room", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ActiveMultiplayerGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("required_answers", models.IntegerField()),
                ("answers_in_current_round", models.IntegerField(default=0)),
                ("round_count", models.IntegerField(default=0)),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True, related_name="active_games", to="api.gameplayer"
                    ),
                ),
                (
                    "wordset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.wordset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="findingwordsactivegame",
            name="activemultiplayergame_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="api.activemultiplayergame",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="raceactivegame",
            name="activemultiplayergame_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="api.activemultiplayergame",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(delete_previous_active_sessions),
    ]
