# Generated by Django 4.2.1 on 2023-12-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_merge_20231118_1610'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordsetuseraccuracy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wordsetuseraccuracy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wordsetuseraccuracy',
            name='wordset',
        ),
        migrations.AlterField(
            model_name='fallingwordsgamesession',
            name='game_name',
            field=models.CharField(choices=[('memory', 'Memory'), ('falling_words', 'Falling Words'), ('finding_words', 'Finding Words'), ('race', 'Race')], default='memory', max_length=20),
        ),
        migrations.AlterField(
            model_name='findingwordsgamesession',
            name='game_name',
            field=models.CharField(choices=[('memory', 'Memory'), ('falling_words', 'Falling Words'), ('finding_words', 'Finding Words'), ('race', 'Race')], default='memory', max_length=20),
        ),
        migrations.AlterField(
            model_name='memorygamesession',
            name='game_name',
            field=models.CharField(choices=[('memory', 'Memory'), ('falling_words', 'Falling Words'), ('finding_words', 'Finding Words'), ('race', 'Race')], default='memory', max_length=20),
        ),
        migrations.AlterField(
            model_name='racegamesession',
            name='game_name',
            field=models.CharField(choices=[('memory', 'Memory'), ('falling_words', 'Falling Words'), ('finding_words', 'Finding Words'), ('race', 'Race')], default='memory', max_length=20),
        ),
        migrations.DeleteModel(
            name='TranslationUserAccuracyCounter',
        ),
        migrations.DeleteModel(
            name='WordSetUserAccuracy',
        ),
    ]
