# Generated by Django 4.2.1 on 2023-12-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_wordsetuseraccuracy_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fallingwordsgamesession',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='findingwordsgamesession',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='memorygamesession',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='racegamesession',
            name='accuracy',
        ),
    ]
