# Generated by Django 4.2.1 on 2023-12-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_waitingroom_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="activemultiplayergame",
            name="total_round_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
