# Generated by Django 4.2.1 on 2023-12-12 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_activemultiplayergame_total_round_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitingroom",
            name="invited_players",
            field=models.ManyToManyField(
                related_name="invited_to", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
