# Generated by Django 4.2.1 on 2023-12-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_remove_fallingwordsgamesession_accuracy_and_more"),
        ("api", "0024_waitingroom_invited_players"),
    ]

    operations = []
